events {}

http {

    upstream message_services {
        server message-service-1:8080;
        server message-service-2:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://message_services;
        }
    }
}