name: Build & Deploy Angular to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: deploy-gh-pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build (prod, correct base)
        run: |
          npx ng build --configuration production --base-href=/burnafter/ --deploy-url=/burnafter/
          # SPA fallback
          cp dist/burnafter-ui/browser/index.html dist/burnafter-ui/browser/404.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist/burnafter-ui/browser

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4

